[project]
name = "krxfetch"
version = "2023.1"
authors = [
  { name="Gunhoon Lee", email="gunhoon@gmail.com" },
]
dependencies = [
    "requests",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
